### ISSUE TITLE
No unit matrix J (all-ones matrix)  used for modulation?

### ISSUE THREAD

**Issue by audio365** [sutd-visual-computing-group/KML-Classification#1]
In gated_conv_net.py,  "weight = weight * w_mod", the weight of convolution kernel seems to have not added the unit matrix J, which is inconsistent with formula 6 of the paper.
In addition, it seems that the code             
"elif 'condition' in layer_name:
x = self.conditional_layer(x, embeddings[layer_name]) if embeddings is not None else x "
has not been used.

**Comment by miladabd** [comment]
Thanks for your comment.

Yes, it seems that in the uploaded version, the residual part is not included. It can be simply added by modifying line 169 in "scripts/models/gated_conv_net.py" as follows:
w_mod = w_mod.view(weight.shape) + torch.ones_like(weight)

The other parts that you mentioned (e.g., conditional_layer) are mainly used in the case of comparison with FiLM (MProtoNet in Tables 1 and 2) and can be activated to reproduce these results by related arguments in the main function.
